import test from "node:test";
import assert from "node:assert/strict";
import {sqlite} from "../scripts/sqlite-adapter.mjs";
import {load,save,engine} from "../backend/repository.js";
import {createFeedback,feedbackInbox,feedbackDetail,updateFeedback} from "../backend/feedback.js";
import {initialUsers} from "../public/roles.js";
import {withIdentities,face} from "../public/identity.js";
import {snapshot,command,bootstrap} from "../backend/service.js";
import {accountConfirmation,closeAccount,processErasure} from "../backend/account-admin.js";
import {newSession} from "../backend/auth.js";
import {publicResponse} from "../backend/public-content.js";
import worker from "../backend/worker.js";
async function fixture(){const e={DB:sqlite(),API_URL:"https://feedback.workers.dev",FRONTEND_URL:"https://example.github.io/NARV/"},b=await load(e.DB),a=structuredClone(b.state);a.users=initialUsers.map(withIdentities).map(u=>({...u,loginKey:"ghh:hidden-"+u.id}));await save(e.DB,b,a);return e}
const input=(changes={})=>({requestId:crypto.randomUUID(),type:"bug",title:"界面响应问题反馈",content:"在消息中心执行具体操作后，页面没有按预期显示更新。请检查相关响应与状态刷新。",evidence:"可复现步骤：打开消息页，切换分类，返回全部。",privateConsent:true,...changes});
const run=(e,u,name,args)=>command(e,u,{name,args});
const uid=async(e,id,side="review")=>face((await load(e.DB)).state.users.find(u=>u.id===id),side).uid;
async function req(e,path,{user,method="GET",body}={}){const token=user?await newSession(e,user):null;return worker.fetch(new Request(e.API_URL+path,{method,headers:{Origin:"https://example.github.io",...(token?{Authorization:"Bearer "+token}:{}),...(method==="POST"?{"Content-Type":"application/json"}:{})},...(method==="POST"?{body:JSON.stringify(body||{})}:{})}),e)}
test("所有反馈需登录；普通作者、AE、访客都不能读取后台",async()=>{const e=await fixture();try{assert.equal((await req(e,"/api/feedback",{method:"POST",body:input()})).status,401);const r=await req(e,"/api/feedback",{method:"POST",user:"demo-author",body:input()});assert.equal(r.status,200);const receipt=await r.json();assert.deepEqual(Object.keys(receipt).sort(),["id","receivedAt"]);for(const who of [undefined,"demo-author","demo-ae","demo-temp"]){const status=who?403:401;assert.equal((await req(e,"/api/feedback",{user:who})).status,status);assert.equal((await req(e,"/api/feedback/"+receipt.id,{user:who})).status,status)}assert.equal((await req(e,"/api/feedback",{user:"demo-original"})).status,200)}finally{e.DB.close()}});
test("私密正文、邮箱与双身份不进入公开数据或普通工作台；通知不含正文",async()=>{const e=await fixture();try{const secret="只供后台查看的隐私证据"+crypto.randomUUID(),d=input({content:secret.repeat(2),contactEmail:"private@example.com",identity:"review"}),r=await createFeedback(e,"demo-author",d),f=await feedbackDetail(e,"demo-editor",r.id);assert.equal(f.reporter.uid,await uid(e,"demo-author"));assert(!JSON.stringify(f).includes(await uid(e,"demo-author","community")));assert(!JSON.stringify(f).includes("ghh:hidden"));assert(!Object.hasOwn(f,"owner_id"));assert(!Object.hasOwn(f,"target_id"));const st=(await load(e.DB)).state;assert(!JSON.stringify(snapshot(st,"demo-author")).includes(secret));assert(!JSON.stringify(await bootstrap(e,"demo-original",{tab:"members"})).includes(secret));const pub=await(await publicResponse(new Request(e.API_URL+"/api/public/catalog"),e)).text();assert(!pub.includes(secret));assert.equal(st.notifications.filter(n=>n.title==="收到新的私密反馈").length,4);assert(!JSON.stringify(st.notifications).includes(secret));assert(!JSON.stringify(st.notifications).includes("private@example.com"));assert.equal((await publicResponse(new Request(e.API_URL+"/api/public/feedback/"+r.id),e)).status,404)}finally{e.DB.close()}});
test("举报Editor只交OE，目标账号与举报者回避；OE举报交其他Editor",async()=>{const e=await fixture();try{const r=await createFeedback(e,"demo-author",input({type:"user_report",targetUid:await uid(e,"demo-editor")}));for(const actor of ["demo-editor","demo-editor-2","demo-author"]){await assert.rejects(feedbackDetail(e,actor,r.id),e=>e.status===403);assert(!(await feedbackInbox(e,actor).catch(()=>({items:[]}))).items.some(f=>f.id===r.id))}assert.equal((await feedbackDetail(e,"demo-original",r.id)).requiredRank,5);const second=await createFeedback(e,"demo-author",input({type:"user_report",targetUid:await uid(e,"demo-original")}));await assert.rejects(feedbackDetail(e,"demo-original",second.id),e=>e.status===403);assert((await feedbackDetail(e,"demo-editor-2",second.id)).highestRoleException);const own=await createFeedback(e,"demo-editor-2",input({type:"user_report",targetUid:await uid(e,"demo-temp")}));await assert.rejects(feedbackDetail(e,"demo-editor-2",own.id),e=>e.status===403);assert((await feedbackInbox(e,"demo-editor")).items.some(f=>f.id===own.id))}finally{e.DB.close()}});
test("固定UID与稿件记录定位审稿人，同名不能误判，也不能读取别人稿件",async()=>{const e=await fixture();try{const d={title:"审稿定位验收",category:"科研与实践",summary:"用于检查自己的稿件对应审稿账号。",content:"真实证据、过程与方法的说明。".repeat(20),consents:{responsibility:true,original:true,privacy:true,policy:true}},s=(await run(e,"demo-author","create",[d])).result;await run(e,"demo-author","action",[s.id,"submit",d]);await run(e,"demo-temp","action",[s.id,"claim"]);await run(e,"demo-temp","action",[s.id,"review",{expectedVersion:1,decision:"revise",note:"需要补充原始数据来源和讨论的适用范围。",conflictFree:true}]);const selected=await createFeedback(e,"demo-author",input({type:"reviewer_report",relatedId:s.id,reviewVersion:1,reviewRound:1}));assert.equal((await feedbackDetail(e,"demo-original",selected.id)).reviewVersion,1);await assert.rejects(createFeedback(e,"demo-author",input({type:"reviewer_report",relatedId:s.id,reviewVersion:2,reviewRound:1})),/审稿意见/);const r=await createFeedback(e,"demo-author",input({type:"reviewer_report",relatedId:s.id}));assert.equal((await feedbackDetail(e,"demo-original",r.id)).targetUid,await uid(e,"demo-temp"));await assert.rejects(createFeedback(e,"demo-reviewer",input({type:"reviewer_report",relatedId:s.id})),/你的稿件/);await assert.rejects(createFeedback(e,"demo-author",input({type:"user_report",targetUid:"重复昵称"})),/完整.*UID/);await assert.rejects(createFeedback(e,"demo-author",input({type:"user_report",targetUid:await uid(e,"demo-author","community")})),/不能举报自己/)}finally{e.DB.close()}});
test("幂等请求重试只建单一次，内容不同不误确认；5条日限额与并发均受保护",async()=>{const e=await fixture();try{const d=input(),both=await Promise.all([createFeedback(e,"demo-author",d),createFeedback(e,"demo-author",d)]);assert.equal(both[0].id,both[1].id);assert.equal((await e.DB.prepare("SELECT count(*) n FROM feedback").first()).n,1);assert.equal((await load(e.DB)).state.notifications.filter(n=>n.title==="收到新的私密反馈").length,4);await assert.rejects(createFeedback(e,"demo-author",{...d,content:d.content+"修改后不能复用原编号。"}),e=>e.status===409);for(let n=0;n<3;n++)await createFeedback(e,"demo-author",input());const racing=await Promise.allSettled([createFeedback(e,"demo-author",input()),createFeedback(e,"demo-author",input())]);assert.equal(racing.filter(r=>r.status==="fulfilled").length,1);assert.equal(racing.find(r=>r.status==="rejected").reason.status,429);assert.equal((await e.DB.prepare("SELECT count(*) n FROM feedback").first()).n,5)}finally{e.DB.close()}});
test("领取、备注、完成、关闭与重新打开都有CAS，防重复处理",async()=>{const e=await fixture();try{const r=await createFeedback(e,"demo-author",input()),racing=await Promise.allSettled(["demo-editor","demo-editor-2"].map(u=>updateFeedback(e,u,r.id,{action:"claim",expectedVersion:1})));assert.equal(racing.filter(r=>r.status==="fulfilled").length,1);const row=await e.DB.prepare("SELECT handler_id FROM feedback WHERE id=?").bind(r.id).first(),handler=row.handler_id,other=handler==="demo-editor"?"demo-editor-2":"demo-editor";await assert.rejects(updateFeedback(e,other,r.id,{action:"resolve",expectedVersion:2,note:"不能抢占其他处理人的任务。"}),e=>e.status===403);await assert.rejects(updateFeedback(e,handler,r.id,{action:"resolve",expectedVersion:1,note:"过时页面不能覆盖新的处理记录。"}),e=>e.status===409);let f=await updateFeedback(e,handler,r.id,{action:"resolve",expectedVersion:2,note:"问题已经复现并修复，内部记录保留在后台。"});assert.equal(f.status,"resolved");assert.equal(f.history.length,2);f=await updateFeedback(e,"demo-original",r.id,{action:"reopen",expectedVersion:3,note:"还需要核查相同条件下的另一处表现。"});assert.equal(f.status,"open");assert.equal(f.handlerName,"");f=await updateFeedback(e,"demo-editor-3",r.id,{action:"claim",expectedVersion:4});f=await updateFeedback(e,"demo-editor-3",r.id,{action:"close",expectedVersion:5,note:"核查后决定关闭，具体依据仅留在后台。"});assert.equal(f.status,"closed");assert(!JSON.stringify(f.history).includes("actor_id"));await assert.rejects(feedbackDetail(e,"demo-author",r.id),e=>e.status===403)}finally{e.DB.close()}});
test("类别、同意、长度、链接及空举报校验；封禁者仍可反馈但不能管理",async()=>{const e=await fixture();try{for(const d of [input({type:"not_a_type"}),input({privateConsent:false}),input({content:"短"}),input({pageUrl:"javascript:alert(1)"}),input({contactEmail:"bademail"}),input({type:"reviewer_report"})])await assert.rejects(createFeedback(e,"demo-author",d));await run(e,"demo-editor","suspendAccount",["demo-author",{action:"permanent",reason:"测试封禁状态下仍可提交私密反馈。"}]);const r=await createFeedback(e,"demo-author",input());assert(r.id);await run(e,"demo-original","suspendAccount",["demo-editor",{action:"permanent",reason:"测试被封禁编辑不能继续读取后台。"}]);await assert.rejects(feedbackDetail(e,"demo-editor",r.id),e=>e.status===403)}finally{e.DB.close()}});
test("列表每页50、按类型状态筛选，标题外不批量返回私密正文",async()=>{const e=await fixture();try{const r=await createFeedback(e,"demo-author",input());for(let n=0;n<51;n++)await e.DB.prepare("INSERT INTO feedback SELECT ?,owner_id,?,title,content,evidence,target_id,target_uid,target_label,related_id,review_version,review_round,required_rank,reporter_name,reporter_uid,reporter_side,contact_email,page_url,status,handler_id,note,history,created_at,updated_at,version,fingerprint,bytes FROM feedback WHERE id=?").bind("F-"+crypto.randomUUID(),n%2?"suggestion":"bug",r.id).run();const first=await feedbackInbox(e,"demo-original"),second=await feedbackInbox(e,"demo-original",{page:2});assert.equal(first.items.length,50);assert(first.next);assert.equal(second.items.length,2);assert(first.items.every(f=>!Object.hasOwn(f,"content")&&!Object.hasOwn(f,"contactEmail")));const selected=await feedbackInbox(e,"demo-original",{type:"suggestion",status:"open"});assert(selected.items.every(f=>f.type==="suggestion"&&f.status==="open"));assert(!selected.next)}finally{e.DB.close()}});
test("注销立即清除自己及针对自己的反馈，其他处理记录解除身份关联",async()=>{const e=await fixture();try{const own=await createFeedback(e,"demo-author",input()),target=await createFeedback(e,"demo-ae",input({type:"user_report",targetUid:await uid(e,"demo-author")}));const c=await accountConfirmation(e,"demo-author",{firstConfirmation:true});await closeAccount(e,"demo-author",{challenge:c.challenge,uid:c.uid,secondConfirmation:true});assert.equal((await e.DB.prepare("SELECT count(*) n FROM feedback WHERE id IN (?,?)").bind(own.id,target.id).first()).n,0);for(let n=0;n<30;n++)if(!await processErasure(e))break;const other=await createFeedback(e,"demo-ae",input());await updateFeedback(e,"demo-editor",other.id,{action:"claim",expectedVersion:1});const closed=await accountConfirmation(e,"demo-original",{targetId:"demo-editor",firstConfirmation:true});await closeAccount(e,"demo-original",{challenge:closed.challenge,uid:closed.uid,secondConfirmation:true});for(let n=0;n<50;n++)if(!await processErasure(e))break;const f=await feedbackDetail(e,"demo-original",other.id);assert.equal(f.status,"open");assert.equal(f.handlerName,"");assert.equal(f.history[0].actor_name,"已注销编辑");assert(!JSON.stringify(f).includes("demo-editor"));assert.equal((await e.DB.prepare("SELECT count(*) n FROM feedback WHERE instr(history,'demo-editor')>0 OR handler_id='demo-editor'").first()).n,0)}finally{e.DB.close()}});
