import test from "node:test";
import assert from "node:assert/strict";
import {sqlite} from "../scripts/sqlite-adapter.mjs";
import {engine,load,loadKeys,save} from "../backend/repository.js";
import {command,bootstrap,scheduled,me,detail} from "../backend/service.js";
import {memberDetail,accountConfirmation,closeAccount,processErasure} from "../backend/account-admin.js";
import {newSession,userFromRequest} from "../backend/auth.js";
import {publicResponse} from "../backend/public-content.js";
import {initialUsers} from "../public/roles.js";
import {withIdentities,face} from "../public/identity.js";
import {canEdit} from "../public/workflow.js";
const draft={title:"生命周期检查",category:"科研与实践",summary:"检查撤回、纠正和账号管理的闭环。",content:"具体研究问题、可靠事实依据和内容局限。".repeat(12),consents:{original:true,privacy:true,policy:true,responsibility:true}};
async function fixture(){const e={DB:sqlite(),API_URL:"https://test.workers.dev"},b=await load(e.DB),a=structuredClone(b.state);a.users=initialUsers.map(withIdentities);await save(e.DB,b,a);return e}
const run=(e,u,name,args)=>command(e,u,{name,args});
async function rejected(e,decision="reject"){const {result:s}=await run(e,"demo-author","create",[draft]);await run(e,"demo-author","action",[s.id,"submit",draft]);await run(e,"demo-temp","action",[s.id,"claim"]);await run(e,"demo-temp","action",[s.id,"review",{decision,note:"已检查依据，当前内容需要重新评估后再考虑发表。",expectedVersion:1,conflictFree:true}]);return s.id}
async function published(e){const id=await rejected(e,"accept");await run(e,"demo-author","action",[id,"publish",{publishConsent:true}]);return id}
async function remedy(e,id,value){const article=(await loadKeys(e.DB,["submissions/"+id])).state.submissions[0],last=article.reviews.filter(r=>r.decision==="accept").at(-1),handler=last.reviewerRank>=2?"demo-ae":"demo-reviewer";const {result:r}=await run(e,"demo-editor-2","report",[id,{reason:"已找到可核实的事实问题，请核对原始材料中与本文结论不一致的记录。"}]);await run(e,handler,"claimAccountability",[r.id]);await run(e,handler,"resolveAccountability",[r.id,{verdict:"upheld",remedy:value,penalty:0,note:"复核原始材料，确认存在上述问题，需要按本次决定处理并说明。",conflictFree:true}])}
test("版本零撤回稿件可删除，已提交撤回稿件仍可修订重投",async()=>{const e=await fixture();try{const {result:s}=await run(e,"demo-original","create",[draft]);await run(e,"demo-original","action",[s.id,"withdraw"]);await run(e,"demo-original","deleteDraft",[s.id]);assert.equal((await loadKeys(e.DB,["submissions/"+s.id])).state.submissions.length,0);const {result:t}=await run(e,"demo-author","create",[draft]);await run(e,"demo-author","action",[t.id,"submit",draft]);await run(e,"demo-author","action",[t.id,"withdraw"]);await run(e,"demo-author","action",[t.id,"save",{...draft,content:"修订草稿内容"}]);const s2=(await detail(e,"demo-author",t.id)).submission;assert.equal(s2.content,draft.content);assert.equal(s2.workingDraft.content,"修订草稿内容");await run(e,"demo-author","action",[t.id,"submit",{...draft,title:"重新提交的版本"}]);assert.equal((await detail(e,"demo-author",t.id)).submission.version,2)}finally{e.DB.close()}});
test("拒稿不允许修改申请，明确允许重投时创建唯一关联新稿",async()=>{const e=await fixture();try{const id=await rejected(e);await assert.rejects(run(e,"demo-author","action",[id,"save",draft]),/许可/);await assert.rejects(run(e,"demo-author","action",[id,"request",{kind:"edit",note:"请求修改原投稿"}]),/流程/);await assert.rejects(run(e,"demo-author","resubmit",[id]),/获准重投/);const invited=await rejected(e,"reject_resubmit"),{result:s}=await run(e,"demo-author","resubmit",[invited]);assert.equal(s.status,"draft");assert.equal(s.version,0);assert.equal(s.resubmissionOf,invited);await assert.rejects(run(e,"demo-author","resubmit",[invited]),/关联/)}finally{e.DB.close()}});
test("caution 保留公开旧版本和作者陈述，修订审核后替换；ban 永久禁止修改",async()=>{const e=await fixture();try{const id=await published(e);await remedy(e,id,"caution");await run(e,"demo-author","action",[id,"statement",{note:"作者补充了原始材料的背景与适用边界，准备进一步更正正文。"}]);await run(e,"demo-author","action",[id,"correction"]);await run(e,"demo-author","action",[id,"save",{...draft,content:"待审核修订正文。".repeat(20)}]);let doc=await(await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).json();assert.equal(doc.article.content,draft.content);assert.equal(doc.article.moderation.kind,"caution");assert(doc.article.authorStatement.text);await run(e,"demo-author","action",[id,"submit",{...draft,content:"待审核修订正文。".repeat(20)}]);doc=await(await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).json();assert.equal(doc.article.content,draft.content);await run(e,"demo-reviewer","action",[id,"claim"]);await run(e,"demo-reviewer","action",[id,"review",{decision:"accept",note:"更正后的事实和适用范围已核实，同意发表。",expectedVersion:2,conflictFree:true}]);await run(e,"demo-author","action",[id,"publish",{publishConsent:true}]);doc=await(await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).json();assert.equal(doc.article.content,"待审核修订正文。".repeat(20));await remedy(e,id,"ban");assert.equal((await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).status,404);await assert.rejects(run(e,"demo-author","action",[id,"save",draft]),/许可/);await assert.rejects(run(e,"demo-author","resubmit",[id]),/获准重投/)}finally{e.DB.close()}});
test("暂时下架未提交超过30天转永久；提交修订解除期限，复审不能降权限",async()=>{const e=await fixture();try{let id=await published(e);await remedy(e,id,"temporary_down");assert.equal((await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).status,404);await run(e,"demo-author","action",[id,"save",draft]);const b=await loadKeys(e.DB,["submissions/"+id]),a=structuredClone(b.state);a.submissions[0].moderation.deadline="2000-01-01T00:00:00.000Z";await save(e.DB,b,a);await assert.rejects(run(e,"demo-author","action",[id,"save",draft]),/期限已过/);await scheduled(e);assert.equal((await detail(e,"demo-author",id)).submission.status,"banned");id=await published(e);await remedy(e,id,"temporary_down");await run(e,"demo-author","action",[id,"submit",draft]);assert.equal((await detail(e,"demo-author",id)).submission.moderation.deadline,null);await assert.rejects(run(e,"demo-temp","action",[id,"claim"]),/不可领取|没有访问权限/);await run(e,"demo-reviewer","action",[id,"claim"])}finally{e.DB.close()}});
test("nothing 不改变正文、公开状态或添加争议标记",async()=>{const e=await fixture();try{const id=await published(e);await remedy(e,id,"nothing");const doc=await(await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).json();assert.equal(doc.article.status,"published");assert.equal(doc.article.content,draft.content);assert.equal(doc.article.accountabilityNotice,"")}finally{e.DB.close()}});
test("已通过申请按稳定账号引用最新昵称，稀疏和已注销身份不会崩溃",async()=>{const e=await fixture();try{await run(e,"demo-author","apply",[{statement:"希望参与相关内容的审阅，提供充分具体的反馈依据。".repeat(2),background:"已完成研究实践并积累相关写作经历，愿意提交背景材料。".repeat(2),integrity:true}]);const a=(await bootstrap(e,"demo-ae",{tab:"applications"})).applications[0];await run(e,"demo-ae","endorse",[a.id,{action:"direct",note:"背景材料已核查，具备长期审阅与反馈能力。"}]);await run(e,"demo-author","updateProfiles",[{community:{name:"同名读者",avatar:"◈"},review:{name:"变更后的评审昵称",avatar:"◇"}}]);const view=await bootstrap(e,"demo-original",{tab:"applications"});assert.equal(view.users.find(u=>u.id===a.userId).review.name,"变更后的评审昵称");assert(view.users.some(u=>u.id==="demo-ae"));assert.equal(face(undefined).name,"已注销账号")}finally{e.DB.close()}});
test("Editor只能封禁低等级账号，封禁禁止写入、可到期恢复",async()=>{const e=await fixture();try{await assert.rejects(run(e,"demo-ae","suspendAccount",["demo-author",{action:"permanent",reason:"具体依据说明，不应允许AE封禁用户。"}]),/Editor/);await assert.rejects(run(e,"demo-editor","suspendAccount",["demo-editor-2",{action:"permanent",reason:"同级账号不应允许封禁操作。"}]),/低于/);await run(e,"demo-editor","suspendAccount",["demo-author",{action:"temporary",until:new Date(Date.now()+3600000).toISOString(),reason:"根据具体事实暂时限制该账号的写入行为。"}]);await assert.rejects(run(e,"demo-author","create",[draft]),/封禁/);await run(e,"demo-editor","suspendAccount",["demo-author",{action:"restore",reason:"问题已妥善处理，现在解除限制。"}]);await run(e,"demo-author","create",[draft]);await run(e,"demo-editor","suspendAccount",["demo-author",{action:"permanent",reason:"违反具体规则，永久限制该账号。"}]);assert((await me(e,"demo-author")).user.suspension.permanent)}finally{e.DB.close()}});
test("删帖删评按真实作者等级校验，永久下架并保留处理通知",async()=>{const e=await fixture();try{const id=await published(e),{result:c}=await run(e,"demo-author","addComment",[id,"评论中的具体背景与证据。".repeat(20),true]);await assert.rejects(run(e,"demo-author","removeContent",["comments",c.id,"不能删除自己或更高权限的内容。"]),/低等级/);await run(e,"demo-editor","removeContent",["comments",c.id,"评论不符合具体规则，经核实删除。"]);assert.equal((await loadKeys(e.DB,["comments/"+c.id])).state.comments[0].status,"removed");await run(e,"demo-editor","removeContent",["submissions",id,"文章违反具体内容规范，永久下架。"]);assert.equal((await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).status,404);assert((await bootstrap(e,"demo-author",{tab:"messages"})).notifications.some(n=>n.title==="内容已下架"))}finally{e.DB.close()}});
test("账号搜索分页和资料页只显示独立身份，社区定位需要Editor原因留痕",async()=>{const e=await fixture();try{const b=await bootstrap(e,"demo-ae",{tab:"members",query:"远岑"});assert(b.users.some(u=>u.id==="demo-reviewer"));assert(!b.users.some(u=>u.id==="demo-author"));const p=await memberDetail(e,"demo-ae","demo-reviewer");assert.equal(p.member.review.name,"远岑");assert(!Object.hasOwn(p.member,"community"));await assert.rejects(memberDetail(e,"demo-author","demo-reviewer"),/AE/);await assert.rejects(bootstrap(e,"demo-ae",{tab:"members",side:"community",query:"林序",reason:"处理具体实名身份相关的复核。"}),/Editor/);const v=await bootstrap(e,"demo-original",{tab:"members",side:"community",query:"林序",reason:"按举报证据定位具体投稿账号，以免同名误判。"});assert(v.users.some(u=>u.id==="demo-author"));assert(v.identityAudits.some(a=>a.query==="林序"))}finally{e.DB.close()}});
test("注销必须两次确认且限本人或OE，立即撤会话，队列删除数据和附件引用",async()=>{const e=await fixture();try{const id=await published(e);await run(e,"demo-temp","toggleBookmark",[id]);const token=await newSession(e,"demo-author");await assert.rejects(accountConfirmation(e,"demo-editor",{targetId:"demo-author",firstConfirmation:true}),/本人或 OE/);await assert.rejects(accountConfirmation(e,"demo-author",{firstConfirmation:false}),/第一次/);const c=await accountConfirmation(e,"demo-author",{firstConfirmation:true});await assert.rejects(closeAccount(e,"demo-author",{challenge:c.challenge,uid:c.uid,secondConfirmation:false}),/第二次/);await closeAccount(e,"demo-author",{challenge:c.challenge,uid:c.uid,secondConfirmation:true});assert.equal(await userFromRequest(new Request(e.API_URL,{headers:{Authorization:"Bearer "+token}}),e),null);assert.equal((await publicResponse(new Request(e.API_URL+"/api/public/articles/"+id),e)).status,404);await assert.rejects(closeAccount(e,"demo-author",{challenge:c.challenge,uid:c.uid,secondConfirmation:true}),/失效/);for(let i=0;i<30;i++)if(!await processErasure(e))break;assert.equal((await loadKeys(e.DB,["users/demo-author"])).state.users.length,0);assert.equal((await e.DB.prepare("SELECT count(*) n FROM entities WHERE instr(head,'demo-author')>0").first()).n,0);assert.equal((await e.DB.prepare("SELECT count(*) n FROM account_erasure").first()).n,0);assert.equal((await loadKeys(e.DB,["submissions/"+id])).state.submissions.length,0);assert.equal((await bootstrap(e,"demo-temp",{tab:"bookmarks"})).bookmarks.length,0)}finally{e.DB.close()}});
test("OE移交原子保留唯一最高权限，移交前不能注销",async()=>{const e=await fixture();try{await assert.rejects(accountConfirmation(e,"demo-original",{firstConfirmation:true}),/移交/);await run(e,"demo-original","transferOE",["demo-editor","经过双方确认，正式移交网站最高管理权限。"]);const s=(await load(e.DB)).state;assert.equal(s.users.filter(u=>u.role==="original_editor").length,1);assert.equal(s.users.find(u=>u.id==="demo-editor").role,"original_editor");assert.equal(s.users.find(u=>u.id==="demo-original").role,"editor");const c=await accountConfirmation(e,"demo-original",{firstConfirmation:true});assert(c.challenge);await assert.rejects(run(e,"demo-original","transferOE",["demo-author","原账号已经失去最高权限，不允许再次移交。"]),/仅 OE/)}finally{e.DB.close()}});

test("永久下架不能被另一未结举报降为caution，关联重投链也不能绕过",async()=>{const e=await fixture();try{const id=await published(e),reason="已发现具体事实问题，需要核对原始记录并据此判断内容质量。".repeat(2);const {result:r1}=await run(e,"demo-editor-2","report",[id,{reason}]),{result:r2}=await run(e,"demo-editor-3","report",[id,{reason}]);await run(e,"demo-reviewer","claimAccountability",[r1.id]);await run(e,"demo-ae","claimAccountability",[r2.id]);await run(e,"demo-reviewer","resolveAccountability",[r1.id,{verdict:"upheld",remedy:"ban",penalty:0,note:"具体事实问题已复核，达到永久下架标准，禁止编辑和重投。",conflictFree:true}]);await assert.rejects(run(e,"demo-ae","resolveAccountability",[r2.id,{verdict:"upheld",remedy:"caution",penalty:0,note:"不同举报不能擅自恢复已永久下架的稿件或绕过原决定。",conflictFree:true}]),/永久下架/);const root=await rejected(e,"reject_resubmit"),{result:child}=await run(e,"demo-author","resubmit",[root]);await run(e,"demo-author","action",[child.id,"submit",draft]);await run(e,"demo-temp","action",[child.id,"claim"]);await run(e,"demo-temp","action",[child.id,"review",{decision:"reject_resubmit",expectedVersion:1,note:"本轮仍未达到标准，允许重新整理后另投。",conflictFree:true}]);await run(e,"demo-editor","removeContent",["submissions",root,"原始稿件违反规定，关联版本不得绕过永久下架。"]);await assert.rejects(run(e,"demo-author","resubmit",[child.id]),/原稿已经永久下架/)}finally{e.DB.close()}});


test("已认领但无意见的主动撤回稿可删除；意见、公开记录与举报下架不能借撤回删除",async()=>{
 const e=await fixture();try{
 const d={...draft,content:draft.content+"\n\n![配图](narv-image:img-1)",images:{"img-1":"data:image/png;base64,aGVsbG8="}},s=(await run(e,"demo-author","create",[d])).result;
 await run(e,"demo-author","action",[s.id,"submit",d]);await run(e,"demo-temp","action",[s.id,"claim"]);await run(e,"demo-author","action",[s.id,"withdraw"]);
 await assert.rejects(run(e,"demo-temp","deleteDraft",[s.id]),/仅作者/);
 await run(e,"demo-author","deleteDraft",[s.id]);
 for(const table of ["entities","records"])assert.equal((await e.DB.prepare("SELECT count(*) AS n FROM "+table+" WHERE key=?").bind("submissions/"+s.id).first()).n,0);
 assert.equal((await e.DB.prepare("SELECT count(*) AS n FROM blob_links WHERE entity_key=?").bind("submissions/"+s.id).first()).n,0);
 assert.equal((await e.DB.prepare("SELECT count(*) AS n FROM entities WHERE kind='notifications' AND json_extract(head,'$.link')=?").bind("#/submission/"+s.id).first()).n,0);
 const accepted=await rejected(e,"accept");await run(e,"demo-author","action",[accepted,"withdraw"]);await assert.rejects(run(e,"demo-author","deleteDraft",[accepted]),/审稿意见/);
 const id=await published(e);await run(e,"demo-author","action",[id,"retract",{note:"作者主动撤回已经公开的稿件。"}]);await assert.rejects(run(e,"demo-author","deleteDraft",[id]),/仅作者/);
 const down=await published(e);await remedy(e,down,"temporary_down");await assert.rejects(run(e,"demo-author","deleteDraft",[down]),/仅作者/);
 }finally{e.DB.close()}
});
